apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: react-dep
  name: react-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-dep
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: react-dep
    spec:
      containers:
      - image: farhat18/react-dep:37
        name: react-dep
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: react-dep
spec:
  type: LoadBalancer
  selector:
    app: react-dep
  ports:
  - protocol: "TCP"
    name: http
    port: 443
    targetPort: 80
