name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  IMAGE_NAME: react-dep

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.run_number }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      
      - name: Update deployment.yaml
        run: |
          # Replace the image in deployment.yaml with the new image
          sed -i "s|farhat18/react-dep.* |${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.run_number }}|" deployment.yaml
          #sed -i "s+farhat18/react-dep.*+tanmay238/images:app-$RUN_NUMBER+g" deployment.yaml
          cat deployment.yaml
      - name: Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add deployment.yaml
          git commit -m "Update deployment.yaml with new Docker image [skip ci]"
          git push origin master
        env:
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}

      #- name: Push changes
       # uses: ad-m/github-push-action@latest
      #  with:
       #   branch: ${{ github.ref }}
        #  github_token: ${{ secrets.GITHUB_PAT }}


     # - name: Update Deployment YAML
       # run: |
       #   sed -i "s|image: farhat18/react-dep:latest|image: ${DOCKER_IMAGE_NAME}:latest|" manifest/deployment.yaml
       #   echo manifest/deployment.yaml
    #    env:
     #     DOCKER_IMAGE_NAME: farhat18/react-dep
